app:
  replicas: 1
  name: product-catalog-ms
  configPath: /app/config
  port: 8090


configMap:
  name: product-catalog-config

image:
  repository: abw12/product-catalog-ms
  tag: v1


postgres:
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  host: db-postgresql-blr1-43787-do-user-15428494-0.c.db.ondigitalocean.com
  port: 25060
  db: absolutehealth
