app:
  replicas: 1
  name: product-catalog-ms
  configPath: /app/config
  port: 8090
configMap:
  name: product-catalog-config
image:
  repository: abw12/product-catalog-ms
  tag: v1
postgres:
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  host: db-postgresql-blr1-67863-do-user-15872635-0.c.db.ondigitalocean.com
  port: 25061
  db: absolutehealth
spaces:
  access_key_id: ${SPACES_ACCESS_KEY_ID}
  secret_key: ${SPACES_SECRET_KEY}
  region: blr1
  baseUrl: https://blr1.digitaloceanspaces.com
  bucketName: absolutehealth