apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  application-dev.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.db }}
        username: {{ .Values.postgres.username }}
        password: {{ .Values.postgres.password }}
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 10
          minimum-idle: 5
          idle-timeout: 300000
          max-lifetime: 1800000
      jpa:
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update
      servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 50MB
      cloud:
        openfeign:
          client:
            config:
              offermgmt-offer-controller:
                url: http://offer-mgmt-ms.absolutehealth.svc.cluster.local:80/offer/v1
    server:
      port: {{ .Values.app.port }}
    spaces:
      access_key_id: {{ .Values.spaces.access_key_id }}
      secret_key: {{ .Values.spaces.secret_key }}
      region: {{ .Values.spaces.region }}
      baseUrl: {{ .Values.spaces.baseUrl }}
      bucketName: {{ .Values.spaces.bucketName }}
    springdoc:
      api-docs:
        path: /v3/productcatalog-docs
